server:
  port: 8001
spring:
  application:
    name: transaction_user
  datasource:
    url: jdbc:mysql://192.168.74.129:3306/transaction_a?characterEncode=UTF8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone:  http://discovery:8761/eureka/
